CREATE TABLE CUSTOMER (
	ID BIGINT IDENTITY NOT NULL PRIMARY KEY,
	NAME VARCHAR(20) NOT NULL,
	MONEY BIGINT NOT NULL
);

INSERT INTO CUSTOMER VALUES (101, "사람1", 0);
INSERT INTO CUSTOMER VALUES (102, "사람2", 0);
INSERT INTO CUSTOMER VALUES (103, "사람3", 0);
INSERT INTO CUSTOMER VALUES (104, "사람4", 0);
INSERT INTO CUSTOMER VALUES (105, "사람5", 0);
INSERT INTO CUSTOMER VALUES (106, "사람6", 0);
INSERT INTO CUSTOMER VALUES (107, "사람7", 0);
INSERT INTO CUSTOMER VALUES (108, "사람8", 0);
INSERT INTO CUSTOMER VALUES (109, "사람9", 0);
