version: '2.2'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ES_VERSION}
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02
      - cluster.initial_master_nodes=es01,es02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=$ES_JAVA_OPTS"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data01:/usr/share/elasticsearch/data
    ports:
      - ${ES1_PORT}:${ES1_PORT}
    networks:
      - elastic

  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ES_VERSION}
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01,es02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=$ES_JAVA_OPTS"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data02:/usr/share/elasticsearch/data
    ports:
      - ${ES2_PORT}:${ES2_PORT}
    networks:
      - elastic

  kib01:
    image: docker.elastic.co/kibana/kibana:${ES_VERSION}
    container_name: kib01
    ports:
      - ${KIBANA_PORT}:${KIBANA_PORT}
    environment:
      ELASTICSEARCH_URL: http://es01:${ES1_PORT}
      ELASTICSEARCH_HOSTS: http://es01:${ES1_PORT}
    networks:
      - elastic

volumes:
  data01:
    driver: local
  data02:
    driver: local

networks:
  elastic:
    driver: bridge
