/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package acktsap.sample

import org.springframework.batch.core.configuration.annotation.EnableBatchProcessing
import org.springframework.batch.extensions.kotlindsl.configuration.EnableBatchDsl
import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.boot.runApplication

@SpringBootApplication
@EnableBatchProcessing
@EnableBatchDsl
class App

fun main() {
    runApplication<App>()
}
