CREATE TABLE CUSTOMER (
	ID BIGINT IDENTITY NOT NULL PRIMARY KEY,
	NAME VARCHAR(20) NOT NULL
);

INSERT INTO CUSTOMER VALUES (1, 'human1');
INSERT INTO CUSTOMER VALUES (2, 'human2');
INSERT INTO CUSTOMER VALUES (3, 'human3');
INSERT INTO CUSTOMER VALUES (4, 'human4');
INSERT INTO CUSTOMER VALUES (5, 'human5');
INSERT INTO CUSTOMER VALUES (6, 'human6');
INSERT INTO CUSTOMER VALUES (7, 'human7');
INSERT INTO CUSTOMER VALUES (8, 'human8');
INSERT INTO CUSTOMER VALUES (9, 'human9');
INSERT INTO CUSTOMER VALUES (10, 'human10');
INSERT INTO CUSTOMER VALUES (11, 'human11');
INSERT INTO CUSTOMER VALUES (12, 'human12');
INSERT INTO CUSTOMER VALUES (13, 'human13');
INSERT INTO CUSTOMER VALUES (14, 'human14');
