spring:
  application:
    name: settle-boot-application-web
  profiles:
    active: local

server:
  shutdown: graceful
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: '*'
